# Generated by Django 5.0.6 on 2024-06-02 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("buyers", "0001_initial"),
        ("users", "0002_remove_userprofile_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="carddetail",
            name="cvv",
            field=models.CharField(default="000", max_length=3),
        ),
        migrations.AlterField(
            model_name="carddetail",
            name="card_number",
            field=models.CharField(max_length=16),
        ),
        migrations.CreateModel(
            name="BuyersProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.userprofile",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="carddetail",
            name="buyer_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cards",
                to="buyers.buyersprofile",
            ),
        ),
        migrations.AlterField(
            model_name="deliveryaddress",
            name="buyer_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="addresses",
                to="buyers.buyersprofile",
            ),
        ),
        migrations.DeleteModel(
            name="BuyerProfile",
        ),
    ]
