# Generated by Django 5.0.6 on 2024-06-02 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_alter_product_seller_profile"),
        ("sellers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="seller_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="sellers.sellerprofile"
            ),
        ),
    ]
