# Generated by Django 5.0.6 on 2024-06-03 02:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_remove_userprofile_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="user_type",
            field=models.CharField(
                choices=[("buyer", "Buyer"), ("seller", "Seller"), ("admin", "Admin")],
                max_length=10,
            ),
        ),
    ]
